name: build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
    paths-ignore:
      [
        ".dockerignore",
        ".gitignore",
      ]
  pull_request:
    paths-ignore:
      [
        ".dockerignore",
        ".gitignore",
      ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: yarn install && yarn build
        
      - if: github.event_name != 'pull_request'
        run: USE_SSH=true yarn deploy