name: build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
    paths-ignore:
      [
        ".dockerignore",
        ".gitignore",
      ]
  pull_request:
    paths-ignore:
      [
        ".dockerignore",
        ".gitignore",
      ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup Git Config
        run: git config user.email "imchensl@163.com" && git config user.name "leon.chen"
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build dist
        run: yarn install && yarn build
        
      - name: Deploy Github Pages
        if: github.event_name != 'pull_request'
        run: GIT_USER=${{ secrets.PAGE_PUSH_USER }} GIT_PASS=${{ secrets.PAGE_PUSH_PASS }} yarn deploy